name: Deploy my-portfolio to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config --global user.email "deorikhiyanat@gmail.com"
          git config --global user.name "Khiyanat-Deori"
          
      - name: Configure Git remote to use SSH
        run: git remote set-url origin git@github.com:Khiyanat-Deori/my-portfolio.git

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install gh-pages
        run: npm install gh-pages --save-dev

      - name: Build
        run: npm run predeploy

      - name: Deploy to GitHub Pages
        run: npx gh-pages -d build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
